### PR TITLE
State to store toggle button features

### PR DESCRIPTION
**Pull request by maharit108**
- feature represented by toggle button is stored in state to be used to create chloropleth of that feature.
- Toggle button to behave like radio buttons on click (1 check others unchecked; none checked allowed)

### CODE REVIEW

**Review by AnansiOmega — APPROVED** [review]
Looks good to me

**Comment by arosenfeld2003** [comment]
Nice work @maharit108!  

A couple comments - would be cleaner not to hardcode all that info... @mcdevittbass and I talked about this before... you can use .map to return the elements with names.  

Here is what I mean:

```
const countyMenus = ['Overall Poverty', 'Child Poverty'];
const countyLabels = ['overall-poverty', 'child-poverty'];
const zipMenus = ['Asian', 'Black', 'Hispanic/Latino', 'Native', 'Pacific', 'White', 'Other', 'Total'];
const zipLabels = ['asian', 'black', 'hispaniclatino', 'native', 'pacific', 'white', 'other', 'total'];

return (
    <div className="menu" id="right-menu">
      <div id="right-menu-county">
        <h2>County Map</h2>
        {countyLabels.map((feature, i) => {
          return (
            <label htmlFor={feature}>
              {countyMenus[i]}
              <input type="checkbox" id={feature} name={feature} className="toggle" onChange={onToggle} checked={selectFeat === feature}></input>
            </label>
          )
        })}
        {currentViewport.zoom > 7 &&
          <div id="right-menu-zipcode">
            <h2>Zipcode Map</h2>
            {zipLabels.map((feature, i) => {
              return (
                <label htmlFor={feature}>
                  {zipMenus[i]}
                  <input type="checkbox" id={feature} name={feature} className="toggle" onChange={onToggle} checked={selectFeat === feature}></input>
                </label>
              )
            })}
          </div>
        }
      </div>
    </div>
  )
```

Also, currently it looks like the logic is backwards - when I toggle the buttons I see state as empty, and then I see the feature state logged when the button is toggled off.

**Comment by maharit108** [comment]
Have made the suggested changes. Please have a look. :)

**Review by arosenfeld2003 — APPROVED** [review]
Looks good!

**Review by arosenfeld2003 — APPROVED** [review]
Looks good.

**Comment by maharit108** [comment]
not to merge yet.... changes is design

**Pull request closed without merging**
