### PR TITLE
Add legend item border and color when selected

### PR DESCRIPTION
**Pull request by KhalfaniW**

### CODE REVIEW

**Review by daleinen7 — CHANGES_REQUESTED** [review]
Can you resolve the merge conflicts? Then I'll take a look at it.

**Comment by KhalfaniW** [comment]
> Can you resolve the merge conflicts? Then I'll take a look at it.

done

**Comment by KhalfaniW** [comment]
Done
________________________________

**Review by daleinen7 — CHANGES_REQUESTED** [review]
Looks good! The only thing I see is the selected option font-weight should be semi-bold and the unselected options should be medium. 
image

**Review by daleinen7 — APPROVED** [review]

**Pull request merged**
